# Generated by Django 4.1.5 on 2023-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado2',
            field=models.BooleanField(default=False),
        ),
    ]
