# Generated by Django 4.1.5 on 2023-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_fecha_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reservada',
            field=models.DateField(null=True),
        ),
    ]
